[hints]
# mapping from output-name-to-warn-on to hint-to-display
matplotlib = """\
    Recipes should usually depend on `matplotlib-base` as opposed to \
    `matplotlib` so that runtime environments do not require large \
    packages like `qt`."""
jpeg = """\
    Recipes should usually depend on `libjpeg-turbo` as opposed to \
    `jpeg` for improved performance. For more information please see \
    https://github.com/conda-forge/conda-forge.github.io/issues/673."""
pytorch-cpu = """\
    Please depend on `pytorch` directly, in order to avoid forcing \
    CUDA users to downgrade to the CPU version for no reason."""
pytorch-gpu = """\
    Please depend on `pytorch` directly. If your package definitely \
    requires the CUDA version, please depend on `pytorch =*=cuda*`."""

# packages that have been renamed
abseil-cpp = "The `abseil-cpp` output has been superseded by `libabseil`."
grpc-cpp = "The `grpc-cpp` output has been superseded by `libgrpc`."
build = "The pypa `build` package has been renamed to `python-build`."
